### ISSUE TITLE
`.widget .sponsor-level .sponsor-logo` の ` max-height` 計算ミスしてました。

### ISSUE THREAD

**Issue by shimakyohsuke** [wckansai2016/site-design#110]
#109 の

``` css
.widget .sponsor-level .sponsor-logo {
    border: 1px solid #CCC;
    padding: 5px;
    margin-top: 10px;
    text-align: center;
    max-height: 300px;
    box-sizing: border-box;
}
```

ですが、正しくは

``` css
.widget .sponsor-level .sponsor-logo {
    border: 1px solid #CCC;
    padding: 5px;
    margin-top: 10px;
    text-align: center;
    max-height: 312px;
}
```

でした。
